### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nerthing** [spekode/sskey#4]
Tried and isn't working.

**Comment by nerthing** [comment]
Windows 7 Professional 64-bit & wedit lcc-win to compile

**Comment by spekode** [comment]
When you say the program runs and ends without prompting anything, you might actually have a working executable. The program does not prompt you for anything. If you run it without arguments, it prints out some help and exits. If you double-clicked the .exe it would appear and immediately disappear.

You should run the program from inside a shell (cmd.exe?).

Alternatively, I have compiled a Windows executable and provided a batch script to run it with the right arguments. It's in the new directory 'windows'. You just put your rescue code into the file "rescue.txt" and run the .bat file.

Let me know if this helps.

**Comment by nerthing** [comment]
It works great, thanks. Any idea why the PHP version isn't working? It 
always gives me an invalid code error. Trying on PHP 5.3

**Comment by spekode** [comment]
Glad you got it working! Did your executable work or did you use the one I provided? Either way, good stuff.

The PHP code is just a frontend a friend of mine wrote. The rescue code calculation is still done by the executable and without the executable it wouldn't do much. I've never actually set up the PHP interface, maybe I should.

**Comment by kaysap** [comment]
I converted this to self-contained Javascript and made it into a neat little HTML page that can be used online and offline. So instead of writing a PHP wrapper for the C program, all the code can now run natively in a browser or in a node server... If you like, I can send you the sources.

**Comment by spekode** [comment]
That would be cool! I'd be happy to take a pull request.

**Comment by kaysap** [comment]
Great! Please check out sskey-js on github...

**Comment by spekode** [comment]
Great work man, looks good. I've added a reference to your port in the readme of this repo.

**Comment by spekode** [comment]
Closing this because the issue was resolved. Always feel free to open a new one or message me directly.
